/*
 * PregX bootstrap file
 *
 * @author bukharim96 <bukharim96@gmail.com>
 */

import { default as getAlphaNumeric } from './src/patterns/alpha-numeric'
import { default as getAlphabet } from './src/patterns/alphabet'
import { default as getBTC } from './src/patterns/btc'
import { default as getCreditCardNumber } from './src/patterns/credit-card-number'
import { default as getDate } from './src/patterns/date'
import { default as getDigits } from './src/patterns/digits'
import { default as getDomain } from './src/patterns/domain'
import { default as getEmail } from './src/patterns/email'
import { default as getGitRepo } from './src/patterns/git-repo'
import { default as getHexColor } from './src/patterns/hex-color'
import { default as getHTMLTag } from './src/patterns/html-tag'
import { default as getIBAN } from './src/patterns/iban'
import { default as getIP } from './src/patterns/ip'
import { default as getIPv4 } from './src/patterns/ipv4'
import { default as getIPv6 } from './src/patterns/ipv6'
import { default as getISBN } from './src/patterns/isbn'
import { default as getMAC } from './src/patterns/mac-address'
import { default as getMD5 } from './src/patterns/md5'
import { default as getPassword } from './src/patterns/password'
import { default as getPhoneNumber } from './src/patterns/phone-number'
import { default as getPOBox } from './src/patterns/po-box'
import { default as getPostalCode } from './src/patterns/postal-code'
import { default as getPrice } from './src/patterns/price'
import { default as getSHA1 } from './src/patterns/sha1'
import { default as getSHA256 } from './src/patterns/sha256'
import { default as getSSN } from './src/patterns/ssn'
import { default as getStreetAddress } from './src/patterns/street-address'
import { default as getTime } from './src/patterns/time'
import { default as getURLSlug } from './src/patterns/url-slug'
import { default as getURL } from './src/patterns/url'
import { default as getUSStateAbbrev } from './src/patterns/us-state-abbrev'
import { default as getUSState } from './src/patterns/us-state'
import { default as getUsername } from './src/patterns/username'
import { default as getUUID } from './src/patterns/uuid'
import { default as getZipcode } from './src/patterns/zipcode'
