/*
 * PregX
 */

export { default as alphaNumeric } from './patterns/alpha-numeric'
export { default as alphabet } from './patterns/alphabet'
export { default as btc } from './patterns/btc'
export { default as creditCardNumber } from './patterns/credit-card-number'
export { default as date } from './patterns/date'
export { default as digits } from './patterns/digits'
export { default as domain } from './patterns/domain'
export { default as email } from './patterns/email'
export { default as gitRepo } from './patterns/git-repo'
export { default as hexColor } from './patterns/hex-color'
export { default as htmlTag } from './patterns/html-tag'
export { default as iban } from './patterns/iban'
export { default as ip } from './patterns/ip'
export { default as ipv4 } from './patterns/ipv4'
export { default as ipv6 } from './patterns/ipv6'
export { default as isbn } from './patterns/isbn'
export { default as macAddress } from './patterns/mac-address'
export { default as md5 } from './patterns/md5'
export { default as password } from './patterns/password'
export { default as phoneNumber } from './patterns/phone-number'
export { default as poBox } from './patterns/po-box'
export { default as postalCode } from './patterns/postal-code'
export { default as price } from './patterns/price'
export { default as sha1 } from './patterns/sha1'
export { default as sha256 } from './patterns/sha256'
export { default as ssn } from './patterns/ssn'
export { default as streetAddress } from './patterns/street-address'
export { default as time } from './patterns/time'
export { default as urlSlug } from './patterns/url-slug'
export { default as url } from './patterns/url'
export { default as usStateAbbrev } from './patterns/us-state-abbrev'
export { default as usState } from './patterns/us-state'
export { default as username } from './patterns/username'
export { default as uuid } from './patterns/uuid'
export { default as zipcode } from './patterns/zipcode'


